{% set name = "hera-workflows" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # for now, replacing source to be git repo, so actual tests can run
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: fd9e120f9e670165d22cce29b8099b9477fab8598424d416d3d461cdfb0c5e60
  git_url: https://github.com/argoproj-labs/hera-workflows.git
  git_rev: 92abd103936b86406632d50d0d0bf9d7119787d5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - argo-workflows
    - pydantic
    - python-dateutil
    - urllib3
    - certifi
    - pytz

test:
  requires:
    - pytest
  source_files:
    - tests/
    - conftest.py
  commands:
    - pytest --durations=5 tests/
  imports:
    - hera.task
    - hera.workflow
    - hera.workflow_service

about:
  home: https://github.com/argoproj-labs/hera-workflows
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Hera is an Argo Workflows Python SDK
  description: |
    Hera is an Argo Workflows Python SDK.
    Hera aims to make workflow construction and submission easy and accessible to everyone!
    Hera abstracts away workflow setup details while still maintaining a consistent vocabulary with Argo Workflows.
  doc_url: https://github.com/argoproj-labs/hera-workflows
  dev_url: https://github.com/argoproj-labs/hera-workflows

extra:
  recipe-maintainers:
    - harelwa
    - bchalk101
