{% set name = "hera-workflows" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # for now, replacing source to be git repo, so actual tests can run
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0e7f48eeaba2d480da1935746bfd55735e2fb42392c6667ad449a3c36aadf65

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - argo-workflows ==6.3.5
    - pydantic
    - python-dateutil
    - urllib3
    - certifi <2022.0.0,>=2021.10.8
    - pytz <2022.0,>=2021.3

test:
  imports:
    - hera.task
    - hera.workflow
    - hera.workflow_service
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/argoproj-labs/hera-workflows
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Hera is an Argo Workflows Python SDK
  description: |
    Hera is an Argo Workflows Python SDK.
    Hera aims to make workflow construction and submission easy and accessible to everyone!
    Hera abstracts away workflow setup details while still maintaining a consistent vocabulary with Argo Workflows.
  doc_url: https://github.com/argoproj-labs/hera-workflows
  dev_url: https://github.com/argoproj-labs/hera-workflows

extra:
  recipe-maintainers:
    - harelwa
    - bchalk101
